use windows_sys::Win32::UI::Input::KeyboardAndMouse::*;

/// Named keyboard keys, using Windows virtual-key codes.
///
/// Letter keys refer to keys, independent of Shift or Caps Lock, rather than text.
/// `Shift`, `Control`, and `Alt` match either side of the keyboard.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Key {
    Backspace = VK_BACK as u8,
    Tab = VK_TAB as u8,
    Enter = VK_RETURN as u8,
    Shift = VK_SHIFT as u8,
    Control = VK_CONTROL as u8,
    Alt = VK_MENU as u8,
    Pause = VK_PAUSE as u8,
    CapsLock = VK_CAPITAL as u8,
    Escape = VK_ESCAPE as u8,
    Space = VK_SPACE as u8,
    PageUp = VK_PRIOR as u8,
    PageDown = VK_NEXT as u8,
    End = VK_END as u8,
    Home = VK_HOME as u8,
    Left = VK_LEFT as u8,
    Up = VK_UP as u8,
    Right = VK_RIGHT as u8,
    Down = VK_DOWN as u8,
    PrintScreen = VK_SNAPSHOT as u8,
    Insert = VK_INSERT as u8,
    Delete = VK_DELETE as u8,
    Num0 = VK_0 as u8,
    Num1 = VK_1 as u8,
    Num2 = VK_2 as u8,
    Num3 = VK_3 as u8,
    Num4 = VK_4 as u8,
    Num5 = VK_5 as u8,
    Num6 = VK_6 as u8,
    Num7 = VK_7 as u8,
    Num8 = VK_8 as u8,
    Num9 = VK_9 as u8,
    A = VK_A as u8,
    B = VK_B as u8,
    C = VK_C as u8,
    D = VK_D as u8,
    E = VK_E as u8,
    F = VK_F as u8,
    G = VK_G as u8,
    H = VK_H as u8,
    I = VK_I as u8,
    J = VK_J as u8,
    K = VK_K as u8,
    L = VK_L as u8,
    M = VK_M as u8,
    N = VK_N as u8,
    O = VK_O as u8,
    P = VK_P as u8,
    Q = VK_Q as u8,
    R = VK_R as u8,
    S = VK_S as u8,
    T = VK_T as u8,
    U = VK_U as u8,
    V = VK_V as u8,
    W = VK_W as u8,
    X = VK_X as u8,
    Y = VK_Y as u8,
    Z = VK_Z as u8,
    Numpad0 = VK_NUMPAD0 as u8,
    Numpad1 = VK_NUMPAD1 as u8,
    Numpad2 = VK_NUMPAD2 as u8,
    Numpad3 = VK_NUMPAD3 as u8,
    Numpad4 = VK_NUMPAD4 as u8,
    Numpad5 = VK_NUMPAD5 as u8,
    Numpad6 = VK_NUMPAD6 as u8,
    Numpad7 = VK_NUMPAD7 as u8,
    Numpad8 = VK_NUMPAD8 as u8,
    Numpad9 = VK_NUMPAD9 as u8,
    Multiply = VK_MULTIPLY as u8,
    Add = VK_ADD as u8,
    Subtract = VK_SUBTRACT as u8,
    Decimal = VK_DECIMAL as u8,
    Divide = VK_DIVIDE as u8,
    F1 = VK_F1 as u8,
    F2 = VK_F2 as u8,
    F3 = VK_F3 as u8,
    F4 = VK_F4 as u8,
    F5 = VK_F5 as u8,
    F6 = VK_F6 as u8,
    F7 = VK_F7 as u8,
    F8 = VK_F8 as u8,
    F9 = VK_F9 as u8,
    F10 = VK_F10 as u8,
    F11 = VK_F11 as u8,
    F12 = VK_F12 as u8,
    NumLock = VK_NUMLOCK as u8,
    ScrollLock = VK_SCROLL as u8,
}

impl From<Key> for u8 {
    fn from(key: Key) -> Self {
        key as Self
    }
}
